#! /bin/bash

cumulative_report_type="cumul"
daily_report_type="daily";

function get_all_states {
	curl -s https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv \
	|  awk -F ',' '{ printf "%-15s\t%-25s\t%-10s\t%-15s\t%s\n", $1, $2, $3, $4, $5 }'
}

function get_single_state {
	get_all_states | grep -i "$1"
}

function get_single_state_deaths_cumulative {
	get_single_state "$1" | awk -F '\t' '{ printf "%-15s\t%s\n", $1, $5 }'
}

function get_single_state_deaths_daily {
	get_single_state "$1" | awk -F '\t' '{ printf "%-15s\t%s\n", $1, $5 - previous; previous = $5 }'
}

function get_single_state_cases_cumulative {
	get_single_state "$1"| awk -F '\t' '{ printf "%-15s\t%s\n", $1, $4 }'
}

function get_single_state_cases_daily {
	get_single_state "$1"| awk -F '\t' '{ printf "%-15s\t%s\n", $1, $4 - previous; previous = $4 }'
}

while getopts ":s:d:c:" opt; do
	case $opt in
		s ) state_flag=true; state=$OPTARG;;
		d ) deaths=true; report_type=$OPTARG;;
		c ) cases=true; report_type=$OPTARG;;
		* ) echo 'Unknown Option:' $OPTARG; exit 1;;
	esac
done

if [ $state_flag ]; then
	if [ $cases ] && [ $report_type == $cumulative_report_type ]; then
		get_single_state_cases_cumulative "$state"

	elif [ $cases ] && [ $report_type == $daily_report_type ]; then
		get_single_state_cases_daily "$state"

	elif [ $deaths ] && [ $report_type == $cumulative_report_type ]; then
		get_single_state_deaths_cumulative "$state"

	elif [ $deaths ] && [ $report_type = $daily_report_type ]; then
		get_single_state_deaths_daily "$state"
	else
		get_single_state "$state"
	fi
else
	get_all_states
fi
